CXX = g++
C = gcc

COMPILER_CALL = $(C) 
SOURCE_FILES = shm_write.cpp
SOURCE_FILES2 = shm_read.cpp


all:
	$(COMPILER_CALL)  $(SOURCE_FILES) -lrt -o write
	$(COMPILER_CALL)  $(SOURCE_FILES2) -lrt -o read
	
